// comentarios.js
// Aquí guardamos todos los textos. El número corresponde a "fotoX.jpeg"

const comentariosFotos = {
    1: "fue muy divertido recostarnos en el pasto mi amor <3",
    2: "me encanta como se ve tu sonrisa cariño <3",
    3: "no podia evitar pensar en lo hermosa que te veias jsjs",
    4: "siempre me ha encantado tu septum",
    5: "esta foto me resulta muy graciosa por mi nariz :D",
    6: "tu ojo tan bonito y el mio tan rojo jajaja",
    7: "te ves tan linda haciendo caras <3",
    8: "esta foto es linda y el sol dio luz de mas jaja",
    9: "haciendo caritas x2, pero me encanta la forma de tu nariz, esta foto la hace notar aun mas <3",
    10: "me gusta mucho como se ve tu cara por tu cabello y el sol <3",
    11: "una mujer muy hermosa y me esta giñando el ojo... espera es mi novia, soy afortunado <3",
    12: "ese dia nos fuimos juntos para enseñarte la ruta y no lo logre pero fue muy divertido <3",
    13: "me encantan mucho tus mejillas, esta foto acentua mi pensamiento... son maravillosas!!",
    14: "exceso de luz del sol otra vez, pero vaya eso ameritaba un beso no? ;D",
    15: "Tú tan preciosa como siempre.",
    16: "me gusta esta foto, tu carita se ve feliz y eso me hace feliz a mi tambien :D",
    17: "una mujer hermosa y al lado su novio con un hoyito es la cabeza jaja",
    18: "vaya, es una foto repetida... no importa, es maravillosa <3",
    19: "otra foto repetida, realmente me encantan... no las quiero borrar <3",
    20: "estaba haciendo mewing mi amor, y se veia que estabas aguantando la risa",
    21: "me encanta el olor de tu bello <3",
    22: "mi mujer bonita, porfin una salida donde te vi y use el traje <3",
    23: "vaya tengo varias fotos repetidas, pero son mi tesoro, me gustan mucho mi amor <3",
    24: "jajaja ahora yo hice caras, que linda saliste cariño",
    25: "ese dia nos dormimos mi amor, recuerdas?",
    26: "vaya mi amor, las mandibulas mas definidas de nuestras casas >:D",
    27: "ese dia me hiciste coletitas jajaja, me encanta como se ve tu cara mi amor <3",
    28: "que preciosa te ves, realmente fue una cita muy divertida mi amor",
    29: "vaya, definitivamente una foto donde mi cara se ve graciosa y tu te ves hermosa <3",
    30: "jsjsjs, se me hace muy tierno como scas tu lengua mi amor :D",
    31: "admirando la creacion de las coletitas jsjsj",
    32: "hacer eso se me hace algo tan intimo y lindo de nosotros <3",
    33: "en esa foto era de nochesita, me gusto mucho como te veias ese dia <3",
    34: "jaja hacemos muchas caras cuando nos tomamos fotos, es realmente muy divertido mi amor <3",
    35: "dos personas sumamente enamoradas viendose a los ojos <3",
    36: "algo especial para ambos y se veia todavia mas linda en ti <3",
    37: "ese dia dormimos mucho mi amor, y te veias muy linda <3",
    38: "tenia un poco de miedo de que no te gustaran mi amor D:",
    39: "fue muy lindo ponernoslas entre nosotros <3",
    40: "jajaja despues de tomar la foto nos dimos cuenta que me la pusiste al reves",
    41: "me gusta mucho como se te ve la pulcera mi amor <3",
    42: "fotito tomada en oxxo, sabias que es tipo de espejo se llama convexo? te amo <3",
    43: "foto maravillosa, eres muy hermosa y ese dia te besuquee mucho <3",
    44: "jajaja me encanta esa mirada de enojo, debes ver a nuestros hijos asi <3",
    45: "otra fotito de esa pulcera mi amor, sabias que pedi especificamente esas cabezas para las pulceras?",
    46: "es muy graciosa esta foto porque la señora sale de fondo jajaja",
    47: "parece la misma foto pero ademas de que te sigues viendo hermosa la señora sigue saliendo de fondo jaja",
    48: "sali con los ojos cerrados amor, hagamos de cuenta que estaba saboreandote por lo hermosa que estas :D",
    49: "en esta foto me gusta muchisisisimo como se ve tu carita mi amor <3",
    50: "realmente me encanta darte un beso <3",
    51: "realmente ese dia estaba bastante despeinado, te ama un loquito :D",
    52: "ese dia fue maravilloso jugar ajedrez contigo mi amor <3",
    53: "estabas planeando tu siguiente movimiento mi amor?",
    54: "casi te ganaba mi amor buajaja",
    55: "me gusta mucho como se ven tus labios mi amor",
    56: "se me antojo mucho darte un beso :3",
    57: "jajajaja literalmente estaba deborandote con la mirada",
    58: "jajaja me encanta tomarte fotos en momentos inesperados <3",
    59: "vaya mi amo... realmente se me antojo un beso justo ahora, me das uno?",
    60: "momento previo al beso jsjsj, ahoraquiero dos besos!!!",
    61: "otro beso mi amor, te necesito justo ahora <3",
    62: "ese dia realmente queria besarte en todo momento, espera... en realidad quiero hacer eso todas nuestras citas!!",
    63: "otra foto maravillosa de este dia <3, me gusta mucho como salimos juntos",
    64: "tus besos saben mejor que cualquiera de mis comidas favoritas <3",
    65: "bueno creo que aqui realmente se ve lo mucho que queria ese beso -///-",
    66: "recuerdo que es dia traias labial... me encanta quitartelo a besos <3",
    67: "quiero uno de esos justo ahota mi amor...",
    68: "me encanta la estructura en general de tu parpado y el como se ven tus ojos, tenemos que transmitirle eso a nuestros hijos",
    69: "quierooooooo un beso tuyo mi amor :,3",
    70: "sabias que tus mejillas me encantan?",
    71: "solo cambia un poco el angulo mi amor, pero te ves taaaan linda <3",
    72: "amooooooor me encantan tus besos :3",
    73: "jaja exceso de chinos ahi mi amor -///-",
    74: "estoy completamente seguro que eres la mujer mas hermosa",
    75: "besoooooo <3",
    76: "soy realmente feliz contigo cariño",
    77: "ese dia... la luz del alumbrado publico te hacia ver tan hermosa",
    78: "te mentiria si te dijera que cada que nos tomamos",
    79: "es increible como solo me gusta tomarme fotos contigo mi amor <3",
    80: "realmente me encanta como se ven tus manos con esmalte negro mi amor",
    81: "jajaja esta foto tambien es muy graciosa mi amor, pero eso no quita que te ves hermosa",
    82: "patitas mi amor, sabes no me he puesto esas botas desde esa cita... es que luego pateaba gente por accidente jeje",
    83: "un dia maravilloso y una mujer maravillosa <3",
    84: "me encanta, sales tu mi amor <3",
    85: "me gusta mucho tu lengua mi amor -///-",
    86: "me encantaaaaan tus manos y aun mas con esmalte negro mi amor... jajajaja estabas muy concentrada poniendome eso en los labios",
    87: "tan hermosa despues de ponerme eso en los labios <3",
    88: "jajajaja esta foto siempre me recuerda al meme del negrito que esta haciendo shhhh con el dedo jajajaja",
    89: "mujer maravillosa :3",
    90: "me gustaron mucho tus uñas ese dia :D",
    91: "una de mis favoritas, me encanta cuando me tomas del brazo",
    92: "sabias que cuando voy vestido asi a la uni me dicen testigo de jehova?",
    93: "te ves tan hermosa, casemonos no?",
    94: "otra vez esta foto maravillosa :3?",
    95: "ese dia fue maravilloso y los mosquitos me hicieron una constelacion en el tobillo",
    96: "esta foto amerita unos besos en la vida real",
    97: "vaya, esa mano... hare eso de nuevo en nuestra proxima cita",
    98: "puedo quedarme tu lengua mi amor?",
    99: "beso en el cabello a una mujer maravillosa, me gusta como te queda el septum",
    100: "esta es la foto numero 100 cuando enliste todas, no es maravillosa?",
    101: "jajajaja otra foto con los ojos cerrados, y tu hermosa como siempre... una foto maravillosa sin dudas!!",
    102: "like, simplemente like... te amo mucho",
    103: "me gusta mucho ese sueter blanco mi amor <3",
    104: "que bonito es tu cabello, no importa el color siempre es maravilloso",
    105: "me gustan mucho tus piernas cariño",
    106: "piernas maravillosas, mujer maravillosa <3",
    107: "amo tus piernas, creo que lo sabes bien -///-",
    108: "me gustan tus tenis mi amor, sabias que yo usaba de ese estilo cuando era pequeño?",
    109: "momentos antes de un beso <3",
    110: "mmmm ahora que lo recuerdo ese dia te bese muchisisimo",
    111: "un dia maravilloso con mi mujer <3",
    112: "ahora yo estoy en un momento like, te amo mucho",
    113: "ese dia recuerdo que nos tomamos muchas fotos, tambien en tu celular <3",
    114: "un beso, esa liga para el cabello aun la guardo <3",
    115: "la mirada de dos personas que se aman intensamente",
    116: "ahora que lo pienso... mi cara se veia un poco rara",
    117: "besos, besos, besos... dame uno porfavor",
    118: "me encanta como se ven tus ojos <3",
    119: "heredale tus ojos a nuestros hijos",
    120: "mas besos, nunca tengo suficiente... son deliciosos!!",
    121: "vaya mi amor, me gusta como me ves -///-",
    122: "amo las fotos donde hacemos caras <3",
    123: "hay que volver a regresarnos juntos mi amor <3",
    124: "jajaja, pobres señores guardias, luces hermosa",
    125: "foto pispireta, acaso hay alguna donde no salgas bien?... no lo creo!!",
    126: "vaya mi amor, esa cara tambien es muy linda <3",
    127: "mmmmm acasa debiamos darnos un beso??... claro que si!!",
    128: "jajaja tan bonitos tus ojos, y los mios tan rojos jsjsjs",
    129: "ahhhhh una mujer hermosa, casemonos <3",
    130: "amo tus mejillas <3",
    131: "ahhhh otra de mis favoritas, me gusta mucho tu perfil mi amor <3",
    132: "maravilloso perfil, te amo mucho <3",
    133: "mmmm me encanta besarte de noche... y de dia tambien <3",
    134: "sueter a rayas y mi mujer es hermosa!!",
    135: "beso <3",
    136: "ese dia estabamos en biblioteca, aun te da nervios entrar??",
    137: "mmmmm mi mujer... hermosa <3",
    138: "en cada respiracion un te amo <3",
    139: "otra de mis favoritas, esta se la enseñe a mi madre",
    140: "mmm me encanta como miras hacia abajo <3",
    141: "me encanta como se ven tus labios",
    142: "tu carita es tan tierna... esta foto me lo recuerda <3",
    143: "inserte carita levantando la ceja <3...",
    144: "ese dia de los quince años te veias sumamente hermosa <3",
    145: "ohhh te ves hermosa tambien cuando cierras los ojos <3",
    146: "me encanta como se ondula tu cabello mi amor",
    147: "te amo demasiado mi amor <3",
    148: "oh vaya mi amor, no recuerdo porque no te bajaste el septum es cita",
    149: "una sonrisa tan maravillosa, espero verte sonreir toda mi vida",
    150: "mmmm acaso no te cansas de ser hermosa?",
    151: "hombre dispuesto a besuquear a su mujer",
    152: "jajaja amo tomarte fotos distraida <3",
    153: "otra foto distrida, amor te amo mucho",
    154: "una foto de tu cabello... me encanta!!",
    155: "jjajaj yo estaba distraido",
    156: "amo todo de ti <3",
    157: "extraño tus besos <,3",
    158: "foto despues de una besuqueada... maravilloso!!",
    159: "mmmm extraño quitarte el labial mi amor <3",
    160: "me encanta cuando te pintas tu cabello mi amor",
    161: "mmmm me falto besarte mas para quitarte mas el labial <3",
    162: "excelente, te quite todo el labial <3",
    163: "besos, besame porfavor <3",
    164: "mmmm se aproxima un comentario mañoso <3",
    165: "amo tus mejillas, las besare en la proxima cita <3",
    166: "mujer, mujer maravillosa <3",
    167: "amo tus besos <3",
    168: "puedo comerte a besos?",
    169: "puedo comerte a besos?",
    170: "amo tanto tus labios... besame 3 horas",
    171: "bye bye",
    172: "cada cita haces que te vea mas hermosa <3",
    173: "amo como se ve tu nariz en esta foto, por cierto es otra de mis favoritas",
    174: "amo como te ves sonriendo en esta foto, tan libre y maravillosa <3",
    175: "casemonos lo antes posible, nada que ver con la foto jajajaj",
    176: "lo que sea con tal de ver sonreir a mi mujer maravillosa <3",
    177: "yo te amo mucho mas <3",
    178: "mucho ojo, mi mujer es hermosa!!",
    179: "mmmm te amo mucho mi amor <3",
    180: "me encanta como se ve tu carita <3",
    181: "apuesto a que ya te habia besado muchisisisimo antes de la foto",
    182: "mmmm hay que besarnos mi amor <3",
    183: "lo recuerdo, estaba respirando tu cabello... me encanta su aroma",
    184: "mi mujer... mi todo <3",
    185: "jajajja estaba concentrado tomando la foto",
    186: "recuerdo que estaba abrazando tu cadera... me encanta tu cadera sabias??",
    187: "otra foto donde simplemente disfruto tu presencia <3",
    188: "tus ojos se ven tan lindos...",
    189: "ese dia se pinto mi cartera, aun tiene la mancha <3",
    190: "besando la mejilla de mi mujer si me disculpa <3",
    191: "jajajja tu cara es tan linda, ya te estaba dando cosquillas mi respiracion",
    192: "momentos despues de pintar una obra maesrtra",
    193: "mujer maravillosa hace que quiera morderla de lo mucho que me gusta",
    194: "recuerdas esa estrella?, le pusimos nuestras iniciales <3",
    195: "beso en la mollera <3",
    196: "una foto repetida pero maravillosa <3",
    197: "carita feliz :)",
    198: "nos quedo dde maravilla <3",
    199: "besito en la cabeza <3",
    200: "ohhh nuestra hija, ese dia nosotros si sacamos peluche y tu hermana no jeje",
    201: "otra fotito de ese dia maravilloso, fue muy lindo pintar juntos <3",
    202: "otra foto de mis favoritas, me encanta como se ve tu cara mi amor <3",
    203: "ahora que lo pienso, tenia los ojos rojos",
    204: "mucho ojo, es mia <3",
    205: "ese dia tambien nos besamos mucho <3",
    206: "ese dia fue muy divertido buscar flores <3",
    207: "patitas, amo tus piernas sabias?",
    208: "mujer maravillosa, al lado un hombre perdidamente enamorado de ella <3",
    209: "patitas y like, perfeccion...",
    210: "jajajaja salgo borroso <3",
    211: "mas patitas, se ensuciaron muy rapido mis botas <3",
    212: "amo lo suave que es tu mano",
    213: "tus manos, tan lindas <3...",
    214: "jajaja me calleron flores en el cabello",
    215: "cabello de dos personas que se aman <3",
    216: "te amo <3",
    217: "recuerdo como yo mismo te puse esa flor en el cabello <3",
    218: "otra de mis favoritas, muy insanos <3",
    219: "mi mujer maravillosa existe a mi lado y yo lo interpreto como coqueteo",
    220: "mmmm hicieron falta mas besos en esa cita <3",
    221: "mmmm acaso me estabas incitando a besarte?",
    222: "like, te amooooooooo <3",
    223: "foto repetida, pero es maravillosa igual <3",
    224: "mmmm te ves tan hermosa <3",
    225: "mmmm unas mejillas tan maravillosas merecen unos besos <3",
    226: "jajaja mi madre vio esta foto <3",
    227: "no sabes cuanto me gusta tocar tus piernas <3",
    228: "mmm acaso estabas a punto de besarme?",
    229: "misma foto mismo sentimiento, amo tus piernas <3",
    230: "anillo que reafirma que nos casaremos <3",
    231: "acaso me retas a unos besos con esa mirada??",
    232: "mmmm mi amor, y un cabello chino <3",
    233: "mmmm acaso me coqueteas con ese guiño?",
    234: "vamos cerrando la boquita, yo te amooo mas <3",
    235: "mas fotitos con el anillo <3",
    236: "oh vaya carita sorprendida... te besare por ello <3",
    237: "jajajja parece que estabamos concentrados por tomar la foto",
    238: "ella es mia <3",
    239: "jajaja justo estaba preparando mi cara para la foto :(",
    240: "like desde otra perspectiva <3",
    241: "patitas <3",
    242: "foto despues de unos besos <3",
    243: "ese dia veia mucho tus piernas -///-",
    244: "mas besitos en la cabeza <3",
    245: "vaya, analisis profundo de la camara mi amor <3",
    246: "mmmm me merezco 2345 besos tuyos <3",
    247: "ohhh ese dia te veias tan maravillos... gracias por dedicarme tu acto y la cancion <3",
    248: "mmmm necesitaba besarte mas ese dia <3",
    249: "bye bye... te amooooo <3",
    250: "ese dia lucias demasiado hermosa...",
    251: "ese dia nos besamos mucho... que se repita!!",
    252: "esta tambien es de mis favoritas... te ves tan guapa <3",
    253: "jajaja miraste hacia otro lado por un momento <3",
    254: "mmmm lo recuerdo despues de esa foto te bese <3",
    255: "jajajaja ese dia nos tomamos la foto sin importar que dijeran los demas <3",
    256: "tan hermosa <3...",
    257: "mmmmm exquisita <3",
    258: "una mujer sumamente hermosa <3",
    259: "un besito en la oreja <3",
    260: "mi mujer, mi niña... te amo <3",
    261: "mmmm tan linda haciendo caras <3",
    262: "tus ojos en esta foto se ven super lindos <3",
    263: "sacando la lengua, te besuqueare por ello <3",
    264: "una foto exquisita, de mis favoritas tambien <3",
    265: "otra foto de los 15, ame tu carita cuando estabas comiendo tu mango jsjsjs",
    266: "otra fotito de cuando volvimos junto por la otra ruta <3",
    267: "mmmm acaso sabes lo mucho que te amo <3?",
    268: "ohhh tan hermosa... casate conmigo <3",
    269: "beso en la mejilla <3",
    270: "beso, delicioso <3",
    271: "oh cuidado con esta es mi zona intima -///-",
    272: "fotito felices <3",
    273: "vaya sin importar que cara hagas me resultas tan hermosa...",
    274: "taaaaan linda <3",
    275: "mujer increible <3",
    276: "esta foto amerita un beso no?",
    277: "durante ese dia no podia dejar de verte... me pase de mañoso <3",
    278: "otra foto mas de los 15, me diverti mucho... gracias mi amor <3",
    279: "jajaja estaba escuchando un audio de mi madre <3",
    280: "ojitos, ojitos... te amo <3",
    281: "me regañaste por morderme el labio :(",
    282: "besito <3",
    283: "beso... son deliciosos amor <3",
    284: "fotito repetida, beso por ello <3",
    285: "nos vemos muy insanos mi amor <3",
    286: "eres mia <3",
    287: "jajaja no recuerdo porque cerre el ojo <3",
    288: "patitas con tenis de bota <3",
    289: "me encanta estar junto a ti <3",
    290: "ohhh tan linda con ese vestido mi amor <3",
    291: "ayy, tus mejillas me matan... son muy lindas!!",
    292: "casi parece que tengo los ojos cerrados jsjsj",
    293: "ojos tan maravillosos que tienes cariño <3",
    294: "fotito repetida, me debes un beso <3",
    295: "amo las caras que haces <3",
    296: "yo soy ese mi amor <3?",
    297: "tu eres esa mi amor <3",
    298: "yo de nuevo mi amor <3, subimos estas fotos a instagram <3",
    299: "ohhh esta foto me recuerda cuanto amo tu cadera y tu vientre <3",
    300: "jajaja los buldak ahi de colados <3",
    301: "ese dia te hice marcas <3",
    302: "fotito de nuestros ojos <3",
    303: "vaya, esa es mi mujer?... soy afortunado <3",
    304: "que no se note que estaba respirando el aroma de tu cabello <3",
    305: "mirando a mi mujer <3",
    306: "disfrutando el momento <3",
    307: "jjajaja tu ojo es hermoso <3",
    308: " mi cabello me pico mi ojito en esa foto... valio la pena!!",
    309: "jajajja mirando a mi mujer <3",
    310: "ese dia fuimos twins, ambos de negro <3",
    311: "fotito en el parque <3",
    312: "analizando el precio del jitomate <3",
    313: "tan lindaaaaaaa <3",
    314: "ahhh tenia tantas ganas de besarte sin parar ese dia <3",
    315: "foto maravillosa que le enseñe a mi madre <3",
    316: "beso en la mejilla <3",
    317: "jajaja tu haciendo caras y yo viendo lo maravillosa que eres <3",
    318: "jajjaja pobre de tu hermana",
    319: "te amo mucho Janeth",
    320: "sabias que...",
    321: "jajaja recuerdo que nos quitamos rapido porque obstruiamos el paso <3",
    322: "blehh... te amo <3",
    323: "fotito repetida, dame un beso <3",
    324: "jajajaja otra vez pobre de tu hermana",
    325: "sabias que... te amo con todo mi ser <3?",
    326: "debimos besarnos mas ese dia <3",
    327: "salimos muy bien en esta foto <3",
    328: "bleeh, yo te amo mucho <3",
    329: "te amo esposa mia <3",
    330: "jsjsjs tu mami nos estaba esperando mientras tomamos fotos <3",
    331: "ambos con los ojos cerrados, pidamos un deseo <3",
    332: "mas fotitos mientras nos esperaban <3",
    333: "fotito repetida, eso significa que me debes un beso <3",
    334: "fotito con otro de nuestros niños y es de la misma especie que tayron <3",
    335: "jjsjsjs inclusos tiene las mejillas rojas <3",
    336: "mujer hermosa me provoca con solo existir",
    337: "jajajaja esta peloooon <3",
    338: "juro que siempre voy peinado a nuestras citas jajaja",
    339: "me gustas demasiado <3",
    340: "nuestro niño nacio pelon :O",
    341: "querias probar mi cabello?, el tuyo sabe rico <3",
    342: "nuestro hijo sigue pelon :(",
    343: "beso fuerte en la mejilla <3",
    344: "beso en el ojo <3",
    345: "amo cada dia contigo <3",
    346: "besooooooooo <3",
    347: "beso, que ricos no?",
    348: "mas besos jsjsj, me das 20 porfis?",
    349: "nos reimos de la calvicie del niño jajaj",
    350: "like de noche <3",
    351: "respirando tu aroma para jamas olvidarlo <3",
    352: "casi un beso, dame 324 por ello <3",
    353: "nunca tengo suficiente de ti <3",
    354: "eso es tan de nosotros... es muy lindo <3",
    355: "mi mujer <3 y yo ",
    356: "nuestro niño pelon <3",
    357: "te amo, te amo, te amo <3",
    358: "nooooo, mi hijo es pelon... *le da un sape",
    359: "te amo <3",
    360: "amo tu cara <3",
    361: "mi mujer hermosa de noche <3",
    362: "mmmm amor... te casarias conmigo?",
    363: "guiñame el ojo si quieres 3243 besos <3",
    364: "amo como te vez en todas las fotos <3",
    365: "es muy lindo estar juntos <3",
    366: "beso y nuestro niño <3",
    367: "amo todo de ti Janeth",
    368: "amo como se ven tus mejillas <3",
    369: "tu sonrisa es maravillosa <3",
    370: "amo como se ven tus mejillas cuando sonries",
    371: "amo cada parte de ti <3",
    372: "fotito... de noche :3",
    373: "nuestro niño <3",
    374: "una mujer sumamente hermosa",
    375: "mi amada Janeth",
    376: "bye bye, que buenas mandibulas <3",
    377: "amo tu piernita <3",
    378: "nos amamos, y eso es maravilloso <3",
    379: "fotito repetida y es la 379 :O",
    380: "tan sonrientes... tan enamorados <3",
    381: "cada parte de ti me pertenece <3",
    382: "tirados en el pasto... un dia maravilloso",
    383: "amo a Janeth Azcona Justo",
    384: "tan lindos tus dientes mi amor <3",
    385: "mas mejillas lindas <3",
    386: "dos enamorados, mas enamorados que dos enamorados",
    387: "ojitos y de fondo el pastito... eso rimo?",
    388: "te extraño mi amor :(",
    389: "ojitos maravillosos <3",
    390: "casi te mimias no mi amor?",
    391: "gracias por ser nosotros <3",
    392: "amo como se ve tu mano <3",
    393: "en tu cuello hacian falta unas marcas mias <3",
    394: "aunque esta es la ultima foto, agradezco infititamente que estes conmigo... agreguemos mas fotos juntos <3",
};